moot.language = {

  // the language code
  $code: 'lt',

  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new posts',
  move: 'Perkelti pokalbio giją',
  moved: 'Pokalbio gija perkelta',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'Nuo',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Diskusijos',
  ch_name: 'Diskusijos pavadinimas',
  ban: 'Ban user',
  banned: 'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days: 'Days',
  forever: 'Forever',
  slogan: 'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",


  warning: 'Warning',
  profanity: 'Profanity is not allowed on this forum. Continued abuse of this policy will result in being banned.',

  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'rodyti',
  hide: 'slėpti',
  invisible: 'Nematomas',
  givebody: 'Žinutės turinys negali būti tuščias.',
  show_old: 'Rodyti seniausius atsakymus',
  show_more: 'Rodyti daugiau atsakymų',
  show_new: 'Rodyti naujausius atsakymus',
  start: 'Pradėti naują temą...',
  error: 'Oi, klaidelė. Prošome nusikopijuoti jūsų žinutę, perkrauti puslapį ir pabandyti vėl. Atsiprašome – mes ištaisysime tai!',
  body: 'Turinio tekstas',
  admin: 'adminas',
  someone: 'Kažkas',
  title: 'Pavadinimas',
  writing: 'dabar rašo...',
  manage: 'Tvarkyti',
  fullview: 'Full view',
  link: 'nuoroda',
  avatar: 'Pakeisti kaukę',

  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logotipas',

  title: 'Title',
  css: 'CSS file',

  single: 'single word',

  username_fail: 'Use letters, numbers or dashes',
  bold: 'bold',
  italics: 'italics',
  monospaced: 'monospaced',

  settings: 'Settings',

  all: 'Visos temos', // or alternatively: All
  anon_1: 'anonimas',  // singular
  anon: 'anonimai',  // plural

  badforum: 'Invalid forum',
  c_acc1: 'Jūsų paskyra įgalinta visose svetainėse, kurios naudoja Muut forumą',
  c_acc: 'Paskyra patvirtinta',
  c_email: 'El. pašto adresas atnaujintas',
  cancel: 'Atsisakyti',
  change: 'Pakeisti',
  changepw: 'Pakeisti slaptažodį',
  close: 'Uždaryti',
  collapse: 'Collapse all',
  comm_count_1: 'comment',  // singular: "1 comment"
  comm_count_n: 'comments',  // plural: "3 comments"
  comment1: 'Būkite pirmas, kuris pakomentavo...',
  comment: 'Komentuoti...',
  edit: 'Redaguoti',
  email: 'El. paštas',
  email_taken: 'Šis el. pašto adresas jau naudojamas',
  emailtip: 'Jūsų el. pašto adresas niekada nebus skelbiamas',
  enter: 'ctrl + enter',
  expired1: 'We just sent you a new one. Please check your email.', // http://d.pr/i/1OEV
  expired: 'This link has expired',
  feed: 'Mano temos', // alternatives: My own, personal

  help2: 'post',
  help3: 'quoted',
  help5: 'code, language guessed',
  help6: 'HTML code',
  in_forum: 'in',
  invalid: 'Invalid value',
  join: 'Join Muut',
  later: 'Later...',
  less: 'less',
  like: 'Like',
  likepost: 'Like this post',
  loading: 'Loading...',
  login: 'Log in',
  login1: 'Log in first',
  login_and: "Login and",

  logout: 'Log out',
  mark: 'Offensive or spam',
  mean: 'Did you mean',
  name: 'Rodomas vardas',
  nametip: 'Jūsų realus vardas, kad žmonės galėtų atpažinti jus',

  newpass: 'Naujas spatažodis',
  noresults: 'No results for',
  nospam: 'Jokių šiukšlių mūsų diskusijų klube!',
  notexist: 'neegzistuoja.',
  ok: 'gerai',
  online: 'Prisijungęs',
  post: 'Post',
  preview: 'Preview',
  progress: ['loading...', 'still working...', 'and working...', 'giving up'],
  reconnect: 'Reconnecting...',
  removepost: 'Remove',
  reply: 'Atsakyti...',
  replybtn: 'Atsakyti',

  saved: 'išsaugota',
  search: 'Paieška',
  select: 'Select channel',
  setup: 'Setup now',
  showing: 'Showing',

  spam: 'Šiukšlės',
  step1: 'We have sent you a confirmation email. Your email is not updated before you complete this step!',
  step: 'Dar vienas žingsnelis',
  terms: 'Aš sutinku su <a>naudojimosi sąlygomis</a>.',
  thanks: 'Ačiū!',
  uname_len: 'Type 4 characters or more',
  uname_taken: 'Šis vardas jau užimtas!',
  unametip: 'This cannot be changed later',
  undo: 'Undo',
  unlike: 'Unlike',
  unspam: 'Not spam',
  unver1: 'Unverified account',
  unver2: 'Please check your email to verify your account.',
  unver3: 'Resend verification link',
  unver4: "Sent. Please check your inbox.",
  unver: 'Unverified',
  unwall: 'unwatch all',
  unwatch: 'Unwatch',
  upgrade2: 'Muut uses WebSockets or CORS for cross domain communication. All modern browsers above Opera 11 and IE7 work.',
  upgrade: 'Please upgrade your browser',
  username_taken: 'This username is taken',
  watch: 'Watch for new replies',
  welcome1: 'Please check your email to complete the registration. If you dont receive email within a minute or two, check your spam folder.',
  welcome2: 'Please provide a Muut username',
  welcome: 'Welcome to Muut',
  you: 'You',

  // times
  now: 'just now',
  months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 'w'

}
